### ISSUE TITLE
Language server not starting on Manjaro install

### ISSUE THREAD

**Issue by awsumatt** [atom/ide-java#104]
- Platform: Manjaro KDE 18.0.4 (64 bit)
- Atom version: 1.36.1
- ide-java version: 0.8.3

On a fresh install of Atom, only 2 apm packages I have installed are `atom-ide-ui` and `ide-java`. When I open a Java file the language server does not start. Here is what is outputted to the console:
```
util.js:1024 Uncaught (in promise) Error: spawn ENOTDIR
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at Promise (/home/user/.atom/packages/ide-java/lib/main.js:90:31)
    at new Promise (<anonymous>)
    at JavaLanguageClient.checkJavaVersion (/home/user/.atom/packages/ide-java/lib/main.js:89:12)
    at JavaLanguageClient.startServerProcess (/home/user/.atom/packages/ide-java/lib/main.js:46:17)
    at JavaLanguageClient.<anonymous> (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/auto-languageclient.js:222:38)
    at Generator.next (<anonymous>)
    at /home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/auto-languageclient.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/auto-languageclient.js:3:12)
    at JavaLanguageClient.startServer (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/auto-languageclient.js:218:16)
    at ServerManager._serverManager.server_manager_js_1.ServerManager [as _startServer] (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/auto-languageclient.js:189:81)
    at ServerManager.<anonymous> (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:122:42)
    at Generator.next (<anonymous>)
    at /home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:3:12)
    at ServerManager.startServer (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:120:16)
    at ServerManager.<anonymous> (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:116:81)
    at Generator.next (<anonymous>)
    at /home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:3:12)
    at ServerManager.getServer (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:102:16)
    at ServerManager.<anonymous> (/home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:61:43)
    at Generator.next (<anonymous>)
    at /home/user/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:7:71
    at new Promise (<anonymous>)
```

**Comment by awsumatt** [comment]
I was a dumb stupid idiot and wrote my path wrong, sorry for the trouble.
