### ISSUE TITLE
Incomplete Classpath Warning

### ISSUE THREAD

**Issue by HyanBatista** [atom/ide-java#117]
There's a problem on idea-java. I open my project folder and it sends to me a message that leads me to this page "https://github.com/atom/ide-java/wiki/Incomplete-Classpath-Warning". I tried to create the file required by the author, however it didn't solve the issue. Others reported the same problem with much deep details so you can better handle the issue, this is the link to the discussion: https://github.com/atom/ide-java/issues/98.

**Comment by piratestatic** [comment]
I am getting the same issue. I noticed it only happens when I enable the Atom IDE package and the Java IDE that goes with it. I can't save anything once that error kicks in.
Using Atom 1.46.0, latest IDE-Java 0.9.0, latest Atom-IDE-ui 0.13.0

I also get this error and can reproduce it multiple times

C:\Users\piratestatic\.atom\packages\atom-ide-ui\modules\atom-ide-ui\pkg\atom-ide-console\lib\main.js

Uncaught (in promise) Error:  
Invariant violation: "activation != null"
    at JavaLanguageClient.sourceInfo (C:\Users\piratestatic\.atom\packages\atom-ide-ui\modules\atom-ide-ui\pkg\atom-ide-console\lib\main.js:276:15)
    at JavaLanguageClient.startExclusiveAdapters (C:\Users\piratestatic\.atom\packages\ide-java\node_modules\atom-languageclient\build\lib\auto-languageclient.js:339:47)
    at JavaLanguageClient.<anonymous> (C:\Users\piratestatic\.atom\packages\ide-java\node_modules\atom-languageclient\build\lib\auto-languageclient.js:269:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\piratestatic\.atom\packages\ide-java\node_modules\atom-languageclient\build\lib\auto-languageclient.js:4:58)

**Comment by piratestatic** [comment]
my work around for this has been to copy pasta everything into a .txt file, turn off packages, close Atom(the issue persist even after uninstalling packages until that session is exited completely), reopen Atom, and open a new file, copy pasta from .txt file, save as "name of old file".
