### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by vitalyster** [atom/ide-java#16]
[Enter steps to reproduce:]

1. Just open Java project

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.0

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\vitalyster\.atom\packages\ide-java\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (native)
    at MessageBuffer.tryReadHeaders (/packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:185:43)
    at /packages/ide-java/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -4:13.5.0 core:backspace (input.hidden-input)
     -4:12.2.0 core:confirm (input.hidden-input)
     -3:15.2.0 editor:newline (input.hidden-input)
  2x -2:58.5.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
ide-java 0.6.0 
```

**Comment by damieng** [comment]
Not able to reproduce this - if you have a reliable minimal repro project please let me know.

**Comment by adelarsq** [comment]
Related with https://github.com/onivim/oni/issues/504
