### ISSUE TITLE
Failed to activate the ide-java package

### ISSUE THREAD

**Issue by myxingkong2017** [atom/ide-java#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.0

### Stack Trace

Failed to activate the ide-java package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-java/lib/main.js:5:44)
    at /packages/ide-java/lib/main.js:163:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-chs-menu 1.0.0 
atom-ide-ui 0.3.1 
atom-simplified-chinese-menu 0.6.5 
ide-flowtype 0.17.0 
ide-java 0.6.0 
ide-typescript 0.1.6 
```

**Comment by 50Wliu** [comment]
Atom 1.21.0 is required for the ide packages.

**Comment by djkago** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.5.3


### Stack Trace

Failed to load the atom-ide-ui package

```
At Cannot find module 'rxjs/bundles/Rx.min.js'

Error: Cannot find module 'rxjs/bundles/Rx.min.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/feature-config.js:7:27)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/feature-config.js:160:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_featureConfig (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:16:50)
    at FeatureLoader.load (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:130:24)
    at /packages/atom-ide-ui/index.js:92:17)
    at /packages/atom-ide-ui/index.js:116:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/index-entry.js:29:18)
    at /packages/atom-ide-ui/index-entry.js:31:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:903:35)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:617:16)
    at config.transact (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:528:23)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/atom-environment.js:821:34
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
atom-maven 1.3.2 
ide-java 0.6.4 
jQuery 1.2.5 
language-scala 1.1.9 
```

**Comment by djkago** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.4


### Stack Trace

Failed to activate the ide-java package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-java/lib/main.js:6:44)
    at /packages/ide-java/lib/main.js:224:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
atom-maven 1.3.2 
ide-java 0.6.4 
jQuery 1.2.5 
language-scala 1.1.9 
```

**Comment by djkago** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.4


### Stack Trace

Failed to activate the ide-java package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-java/lib/main.js:6:44)
    at /packages/ide-java/lib/main.js:224:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.21.1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.21.1/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
atom-languageclient 0.6.4 
atom-maven 1.3.2 
ide-java 0.6.4 
jQuery 1.2.5 
language-scala 1.1.9 
```

**Comment by djkago** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.6.4


### Stack Trace

Failed to activate the ide-java package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-java/lib/main.js:6:44)
    at /packages/ide-java/lib/main.js:224:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.21.0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
ide-java 0.6.4 
```
