### ISSUE TITLE
Exception Thrown from Gradle Project

### ISSUE THREAD

**Issue by keplersj** [atom/ide-java#2]
[Enter steps to reproduce:]

1. Open Gradle Project

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [languageserver-java](https://github.com/atom/languageserver-java) package 0.1.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/kepler/Developer/atom/languageserver-java/node_modules/vscode-jsonrpc/lib/messageReader.js:181

Error: Header must provide a Content-Length property.
  at StreamMessageReader.onData (/Users/kepler/Developer/atom/languageserver-java/node_modules/vscode-jsonrpc/lib/messageReader.js:181:27)
  at Socket.<anonymous> (/Users/kepler/Developer/atom/languageserver-java/node_modules/vscode-jsonrpc/lib/messageReader.js:166:19)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at Pipe.onread (net.js:543:20)

```

### Commands

```
     -1:31.6.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
ascii-art 1.2.0 
atom-language-server-protocol 0.0.0 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.10 
autoclose-html 0.23.0 
autocomplete-python 1.8.63 
crystal 0.2.0 
editorconfig 2.2.2 
file-icons 2.1.4 
graphql-autocomplete 0.4.1 
hyperclick 0.0.40 
language-babel 2.57.7 
language-crystal-actual 0.33.0 
language-docker 1.1.7 
language-graphql 0.8.0 
language-groovy 0.6.0 
language-llvm 0.1.1 
language-minecraft-forge-cfg 0.1.2 
language-rust 0.4.10 
languageserver-java 0.1.0 
lcov-info 0.12.0 
linter-eslint 8.1.6 
linter-pycodestyle 2.0.2 
linter-rust 0.8.0 
linter-xo 0.22.0 
merge-conflicts 1.4.4 
minimap 4.27.1 
nuclide 0.219.0 
nuclide-test-runner-jest 0.3.0 
pigments 0.39.1 
pretty-json 1.6.3 
racer 0.20.0 
tokamak 0.3.2 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
xml-formatter 0.10.0 
```

**Comment by keplersj** [comment]
Not this package's problem. Was trying to open a Android project which the server doesn't support.

**Comment by damieng** [comment]
Ah, thanks for letting me know. Maybe somebody will create an Android capable language server in the future!
