### ISSUE TITLE
Language server download getting 404

### ISSUE THREAD

**Issue by tylerFowler** [atom/ide-java#33]
After the last update (to v0.6.4) I found there were some "classpath incomplete" errors and so I reinstalled the package only to get this in the console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.5.0-201709251422.tar.gz Fetch complete: GET "http://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.5.0-201709251422.tar.gz".
/Users/tylerfowler/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/download-file.js:77 Uncaught (in promise) Error: Unable to download, server returned 404 Not Found
    at /Users/tylerfowler/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/download-file.js:77:13
    at Generator.next (<anonymous>)
    at step (/Users/tylerfowler/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/download-file.js:56:191)
    at /Users/tylerfowler/.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/download-file.js:56:361
```

And sure enough, that URL does give a 404 not found.

**Comment by damieng** [comment]
Hmm, that's weird. I just tried that url in my browser and it prompted to download it.

Are you behind any kind of proxy?

**Comment by tylerFowler** [comment]
Hm.. actually just tried it again and it worked, must've been a fluke thing. I am in China at the moment so maybe just some VPN weirdness. Disregard this one :wink:
