### ISSUE TITLE
[SOLVED] The package does nothing - "This is likely an error with the language package"

### ISSUE THREAD

**Issue by Adalann** [atom/ide-java#54]
I'm using the 1.23.3 version of Atom and my packages are up to date.
I have atom-ide-ui installed.
As we can see here, java is installed too :
![git](https://user-images.githubusercontent.com/26391428/35585351-fc1cfa0a-05f7-11e8-9335-67406f86b16e.png)

I've also set up the java path :
![java_path](https://user-images.githubusercontent.com/26391428/35585482-4f1412d4-05f8-11e8-8ef5-ad436c951897.png)

But when I open a java file, nothing is happening, no error detection or auto-completion.
Furthermore, when I toggle the outline panel I have this message :
![outline](https://user-images.githubusercontent.com/26391428/35585706-fdc4ae74-05f8-11e8-8d34-89ecd559acfc.png)

Do you have an idea about what's going on ?

**Comment by damieng** [comment]
Can you open the dev tools window to see if there are any errors there.

**Comment by Adalann** [comment]
Yep, this is the output :
![errors](https://user-images.githubusercontent.com/26391428/35586312-cf990250-05fa-11e8-83df-b032926a84a1.png)

**Comment by Adalann** [comment]
If I switch off the id-php, this is quite more complex :

> Uncaught (in promise) Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at Promise (/home/theo/.atom/packages/ide-java/lib/main.js:84:31)
    at JavaLanguageClient.checkJavaVersion (/home/theo/.atom/packages/ide-java/lib/main.js:83:12)
    at JavaLanguageClient.startServerProcess (/home/theo/.atom/packages/ide-java/lib/main.js:40:17)
    at JavaLanguageClient.startServer (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/auto-languageclient.js:271:28)
    at ServerManager._serverManager._serverManager.ServerManager.p [as _startServer] (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/auto-languageclient.js:237:70)
    at ServerManager.startServer (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:142:34)
    at ServerManager.getServer (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:137:73)
    at ServerManager._handleTextEditor (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:79:33)
    at ServerManager._handleGrammarChange (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:94:12)
    at editor.observeGrammar.grammar (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:70:60)
    at TextEditor.observeGrammar (/usr/share/atom/resources/app/src/text-editor.js:727:11)
    at ServerManager.observeTextEditors (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:70:29)
    at Set.forEach (native)
    at TextEditorRegistry.observe (/usr/share/atom/resources/app/src/text-editor-registry.js:170:26)
    at ServerManager.startListening (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:54:45)
    at JavaLanguageClient.activate (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/auto-languageclient.js:238:25)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:255:25)
    at /usr/share/atom/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at /usr/share/atom/resources/app/src/atom-environment.js:865:36
util.js:1022 Uncaught (in promise) Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at Promise (/home/theo/.atom/packages/ide-java/lib/main.js:84:31)
    at JavaLanguageClient.checkJavaVersion (/home/theo/.atom/packages/ide-java/lib/main.js:83:12)
    at JavaLanguageClient.startServerProcess (/home/theo/.atom/packages/ide-java/lib/main.js:40:17)
    at JavaLanguageClient.startServer (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/auto-languageclient.js:271:28)
    at ServerManager._serverManager._serverManager.ServerManager.p [as _startServer] (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/auto-languageclient.js:237:70)
    at ServerManager.startServer (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:142:34)
    at ServerManager.getServer (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:137:73)
    at ServerManager._handleTextEditor (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:79:33)
    at ServerManager._handleGrammarChange (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:94:12)
    at editor.observeGrammar.grammar (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:70:60)
    at TextEditor.observeGrammar (/usr/share/atom/resources/app/src/text-editor.js:727:11)
    at ServerManager.observeTextEditors (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:70:29)
    at Set.forEach (native)
    at TextEditorRegistry.observe (/usr/share/atom/resources/app/src/text-editor-registry.js:170:26)
    at ServerManager.startListening (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/server-manager.js:54:45)
    at JavaLanguageClient.activate (/home/theo/.atom/packages/ide-php/node_modules/atom-languageclient/build/lib/auto-languageclient.js:238:25)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:255:25)
    at /usr/share/atom/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at /usr/share/atom/resources/app/src/atom-environment.js:865:36

**Comment by rsese** [comment]
I checked my package settings and see that the `Java Home` setting is set to the default value for me though the executable is in the same directory for me:

```
$ which java
/usr/bin/java
```

I see the setting says "path to Java 8 or later home folder" but your screenshot shows that you have it set to the executable `/usr/bin/java`.  Can you try leaving it at the default value or if that doesn't work, set it to `/usr`?  `/usr/bin` didn't work for me, it looks like we tack on `/bin` automatically?

https://github.com/atom/ide-java/blob/4f7541456f1de96a67b6a52e4b9d2571a5ec9253/lib/main.js#L147

**Comment by Adalann** [comment]
I tried to let the Java home field as blank Atom raised theses errors :
![java-error](https://user-images.githubusercontent.com/26391428/35826265-887dae8a-0ab8-11e8-94c5-0516dfdbb577.png)

The same errors popup when I set the path as /usr.
I tried /usr/bin and I got this message :
![java-error-2](https://user-images.githubusercontent.com/26391428/35826329-c2d4f552-0ab8-11e8-9ac0-018670e59c0d.png)

With /usr/bin/java, it's seems fine for the java path, but the package still not working.
According to the dev tool, this is a problem with the server-manager module

**Comment by 50Wliu** [comment]
It looks like the default Java Home setting is correct (i.e. you are getting openjdk version info back) but ide-java doesn't know how to interpret it.

**Comment by Adalann** [comment]
Well it's fixed.
I downloaded the jdk from the oracle website instead of using the openjdk of my disrto and it's working pretty well.
Thank's you for your help everyone !
