### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Zinnig** [atom/ide-java#85]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: IPC
**Thrown From**: [ide-java](https://github.com/atom/ide-java) package 0.8.3

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At buffer.js:10

RangeError: Maximum call stack size exceeded
    at FastBuffer (buffer.js:10:14)
    at Buffer.slice (buffer.js:833:10)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:242:21)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:250:8)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:250:8)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:250:8)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:250:8)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:250:8)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/packages/ide-java/node_modules/tar-stream/extract.js:250:8)
    at Extract._continue (/packages/ide-java/node_modules/tar-stream/extract.js:213:28)
    at oncontinue (/packages/ide-java/node_modules/tar-stream/extract.js:68:10)
    at Extract.onheader (/packages/ide-java/node_modules/tar-stream/extract.js:132:7)
```

### Commands

```
  2x -9:24.5.0 core:backspace (input.hidden-input)
     -9:22.6.0 core:confirm (input.hidden-input)
  4x -9:03.7.0 core:backspace (input.hidden-input)
     -9:03.0 core:confirm (input.hidden-input)
  2x -8:42.3.0 core:backspace (input.hidden-input)
     -8:27 core:confirm (input.hidden-input)
     -8:09.4.0 core:backspace (input.hidden-input)
     -8:07.0 core:confirm (input.hidden-input)
  3x -7:54.9.0 core:backspace (input.hidden-input)
     -7:27.9.0 fuzzy-finder:toggle-file-finder (div.tool-panel.tree-view)
     -6:06.7.0 core:backspace (input.hidden-input)
     -6:01.5.0 core:page-down (input.hidden-input)
     -6:00.8.0 core:confirm (input.hidden-input)
     -3:52.7.0 fuzzy-finder:toggle-file-finder (div.panels-item)
     -1:40.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:30.4.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
ide-cpp 0.0.3 
ide-csharp 0.6.2 
ide-css 0.3.0 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-php 0.7.14 
ide-python 1.0.0 
```

**Comment by rsese** [comment]
Thanks for the report! Do you remember what you were doing at the time of the error? Also, is the error is reproducible?
